# https://aka.ms/yaml

jobs:
- job: 'Build_macOS'
  pool:
    vmImage: 'macos-10.15'
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Checkout Submodules'
  - script: TERM="" bash ./CI/build-deps-macos.sh -a x86_64
    displayName: 'Build dependencies'
  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './macos'
      artifactName: osx-deps
