# https://aka.ms/yaml

jobs:
- job: 'Build_macOS'
  pool:
    vmImage: 'macos-10.15'
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Checkout Submodules'
  - script: ./osx-install-tools.sh
    displayName: 'Install Tools'
  - script: ./build-package-deps-osx.sh
    displayName: 'Build And Package'

  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './osx'
      artifactName: osx-deps

- job: 'Build_Win32'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: ./win-install-tools.sh
    displayName: 'Install Tools'
  - script: ./win32.sh
    displayName: 'Build deps'

  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './ffmpeg/ffbuild'
      artifactName: ffmpeglogs

  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './win32'
      artifactName: win32-deps

- job: 'Build_Win64'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: ./win-install-tools.sh
    displayName: 'Install Tools'
  - script: ./win64.sh
    displayName: 'Build deps'

  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './ffmpeg/ffbuild'
      artifactName: ffmpeglogs

  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './win64'
      artifactName: win64-deps
