name: 'Build FFmpeg'
description: 'Builds FFmpeg for obs-deps with specified architecture, type, and build config'
inputs:
  target:
    description: 'Build target for FFmpeg'
    required: true
  type:
    description: 'Build type (shared or static libraries)'
    required: false
    default: 'static'
  config:
    description: 'Build configuration'
    required: false
    default: 'Release'
  cacheRevision:
    description: 'Cache revision number to force creation of new cache generation'
    required: false
    default: '01'
runs:
  using: 'composite'
  steps:
    - name: Environment Setup
      id: ffmpeg-env-setup
      shell: bash
      run: |
        case "${{ runner.os }}" in
          Linux)
            if ! type zsh > /dev/null 2>&1; then
              sudo apt update
              sudo apt install zsh
            fi
            ;;
          macOS)
            if ! type sha256sum > /dev/null 2>&1; then
              brew install coreutils
            fi
        esac

        ffmpeg_dep_hash=$(cat ${{ github.workspace }}/deps.ffmpeg/*.zsh | sha256sum | cut -d " " -f 1)
        echo "hash=${ffmpeg_dep_hash}" >> $GITHUB_OUTPUT

    - name: Restore FFmpeg Dependencies from Cache
      id: ffmpeg-deps-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/*_build_temp/*
          !${{ github.workspace }}/*_build_temp/**/.git
          !${{ github.workspace }}/*_build_temp/*.tar.gz
          !${{ github.workspace }}/*_build_temp/*.tar.xz
          !${{ github.workspace }}/*_build_temp/*.zip
          !${{ github.workspace }}/*_build_temp/FFmpeg*
          !${{ github.workspace }}/*_build_temp/x264-*-shared/
        key: ${{ inputs.target }}-ffmpeg-deps-${{ inputs.type }}-${{ steps.ffmpeg-env-setup.outputs.hash }}-${{ inputs.cacheRevision }}

    - name: Build and Install FFmpeg Dependencies
      if: ${{ steps.ffmpeg-deps-cache.outputs.cache-hit != 'true' }}
      shell: zsh {0}
      run: ./build-ffmpeg.zsh '*~ffmpeg' --target ${{ inputs.target }} --config ${{ inputs.config }} --${{ inputs.type }}

    - name: Restore FFmpeg from Cache
      id: ffmpeg-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/*_build_temp/FFmpeg*/*
          !${{ github.workspace }}/*_build_temp/FFmpeg*/.git
        key: ${{ inputs.target }}-ffmpeg-${{ inputs.type }}-${{ steps.ffmpeg-env-setup.outputs.hash }}-${{ inputs.cacheRevision }}

    - name: Install FFmpeg
      if: ${{ steps.ffmpeg-cache.outputs.cache-hit == 'true' }}
      shell: zsh {0}
      run: ./build-ffmpeg.zsh --skip-build --skip-unpack --target ${{ inputs.target }} --config ${{ inputs.config }} --${{ inputs.type }}

    - name: Build and Install FFmpeg
      if: ${{ steps.ffmpeg-cache.outputs.cache-hit != 'true' }}
      shell: zsh {0}
      run: ./build-ffmpeg.zsh --target ${{ inputs.target }} --config ${{ inputs.config }} --${{ inputs.type }}
