#!/usr/bin/env bash

set -eE

info() {
    echo -e "${COLOR_ORANGE}  + ${1}${COLOR_RESET}"
}

error() {
     echo -e "${COLOR_RED}  + ${1}${COLOR_RESET}"
}

obs-deps-patch-main() {
    if [ $# -ne 2 ]; then
        error "Usage: apply_patch PATCH_URL PATCH_HASH"
        return 1
    fi

    COMMIT_URL="${1}"
    COMMIT_HASH="${2}"
    PATCH_FILE="$(basename ${COMMIT_URL})"

    curl --retry 5 --progress-bar -L -O "${COMMIT_URL}"
    if [ "${COMMIT_HASH}" = "$(sha256sum ${PATCH_FILE} | cut -d " " -f 1)" ]; then
        info "${PATCH_FILE} downloaded successfully and passed hash check"
    else
        error "${PATCH_FILE} downloaded successfully and failed hash check"
        return 1
    fi

    info "Applying patch ${COMMIT_URL}"
    patch -g 0 -f -p1 -i "${PATCH_FILE}"
}

obs-deps-patch-main $*