#!/usr/bin/env bash

set -eE

info() {
    echo -e "${COLOR_ORANGE}  + ${1}${COLOR_RESET}"
}

error() {
     echo -e "${COLOR_RED}  + ${1}${COLOR_RESET}"
}

obs-deps-fetch-main() {
    if [ $# -ne 2 ]; then
        error "Usage: safe_fetch URL HASH"
        return 1
    fi

    DOWNLOAD_URL="${1}"
    DOWNLOAD_HASH="${2}"
    DOWNLOAD_FILE="$(basename ${DOWNLOAD_URL})"

    curl --retry 5 --progress-bar -L -O "${DOWNLOAD_URL}"
    if [ "${DOWNLOAD_HASH}" = "$(sha256sum ${DOWNLOAD_FILE} | cut -d " " -f 1)" ]; then
        info "${DOWNLOAD_FILE} downloaded successfully and passed hash check"
        return 0
    else
        error "${DOWNLOAD_FILE} downloaded successfully and failed hash check"
        return 1
    fi
}

obs-deps-fetch-main $*