name: build_macos

on:
  push:
    branches: 
      - master
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Tools
        if: success()
        shell: bash
        run: ./osx-install-tools.sh
      - name: Get Current Date
        shell: bash
        id: get_date
        run: echo ::set-output name=CURRENT_DATE::$(date +"%Y-%m-%d")
      - name: Build and Package
        if: success()
        shell: bash
        run: ./build-package-deps-osx.sh
      - name: PublishBuildArtifacts
        if: success() && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v2-preview
        with:
          name: '${{ steps.get_date.outputs.CURRENT_DATE }}'
          path: ./osx/*.tar.gz
