name: build_macos

on:
  push:
    paths:
      - '.github/workflows/build_deps.yml'
      - '.github/workflows/create_scripts.yml'
    branches:
      - master

jobs:
  create_scripts:
    name: "Generate build scripts"
    runs-on: [ubuntu-latest]
    if: github.ref == 'refs/heads/master'
    env:
      CHECKOUT_REF: ${{ github.ref }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: 'Restore Pip cache'
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docgen
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: 'Python environment setup'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64
      - name: 'Generate docs'
        shell: bash
        run: |
          set -e
          echo "  + Generating build scripts"

          git fetch origin
          git checkout ${CHECKOUT_REF/refs\/heads\//}

          python -m pip install pyyaml
          python build_script_generator.py ./.github/workflows/build_deps.yml

          echo "  + Build scripts successfully generated"

          if git diff --quiet; then
            echo "  + No script changes changes to commit";
            exit 0;
          fi

          REMOTE_URL="$(git config remote.origin.url)"
          TARGET_REPO=${REMOTE_URL/https:\/\/github.com\//github.com/}
          GITHUB_REPO=https://${GITHUB_TOKEN:-git}@$TARGET_REPO

          git config user.name "Github Actions CI"
          git config user.email "${{ github.event.pusher.email }}"

          git add build-script-*
          git pull
          git commit -m "CI: Update build scripts - $(git rev-parse --short HEAD)"
          git push -q $GITHUB_REPO
